services:

    async:
        image: ${COMPOSE_PROJECT_NAME}/app
        container_name: ${SAIL_SERVICE_ASYNC}
        extra_hosts:
            - host.docker.internal:host-gateway
            - gateway.docker.internal:host-gateway
        environment:
            SAIL_ENV: ${SAIL_ENV}
            SERVER_ENVIRONMENT: ${SERVER_ENVIRONMENT}
            SERVER_MODE: async
            SERVER_LABEL: ${SAIL_PROJECT}-${SAIL_SUBPROJECT}/async
            SAIL_GROUPID: ${SAIL_GROUPID}
            SAIL_USERID: ${SAIL_USERID}
            SAIL_USERNAME: ${SAIL_USERNAME}
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            ASYNC_NUMPROCS: ${SAIL_SERVICE_ASYNC_NUMPROCS}
            WORKER_CONNECTION: ${SAIL_SERVICE_ASYNC_CONNECTION}
            WORKER_QUEUE: ${SAIL_SERVICE_ASYNC_QUEUE}
            WORKER_MAX_JOBS: ${SAIL_SERVICE_ASYNC_MAX_JOBS}
        volumes:
            - ../../:/var/www/html
        networks:
            - sail-project-net
            - sail-net
