services:

    mysql:
        build:
            context: ./mysql
            dockerfile: Dockerfile
        image: ${COMPOSE_PROJECT_NAME}/mysql:8.0
        container_name: ${SAIL_SERVICE_MYSQL}
        ports:
            - ${MYSQL_FORWARD_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
        volumes:
            - 'sail-mysql-vol:/var/lib/mysql'
        networks:
            - sail-project-net
            - sail-net
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
            retries: 3
            timeout: 5s

volumes:
    sail-mysql-vol:
        driver: local
        name: ${COMPOSE_PROJECT_NAME}-mysql-vol
